# SOPS configuration
# Defines which age public key to use for encrypting secrets.
# The corresponding private key must be available to Argo CD repo-server
# via the sops-age-key Kubernetes secret.
creation_rules:
  - path_regex: \.sops\.yaml$
    age: >-
      age17r5p9rzudxc8s3e6mdlwjalh2q7mpq77c69sqwwcg4f838j4fafqn6689a
