# KSOPS generator — tells kustomize to decrypt SOPS-encrypted files.
# Argo CD's repo-server runs kustomize with --enable-alpha-plugins --enable-exec,
# which triggers KSOPS to decrypt using the age key mounted at /app/config/age/keys.txt.
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: pg-credentials-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /usr/local/bin/ksops
files:
  - pg-credentials.sops.yaml
