# CloudNativePG PostgreSQL Cluster
# Right-sized for ~5k IoT devices with ~50% headroom.
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fluodata-pg
  namespace: fluodata
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    storageClass: longhorn
    size: 10Gi

  walStorage:
    storageClass: longhorn
    size: 2Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

  postgresql:
    parameters:
      # Connection handling
      max_connections: "200"
      # Memory
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      work_mem: "4MB"
      maintenance_work_mem: "128MB"
      # WAL (sized to fit 2Gi WAL volume)
      min_wal_size: "64MB"
      max_wal_size: "512MB"
      wal_buffers: "8MB"
      # Checkpoints
      checkpoint_completion_target: "0.9"
      # Logging
      log_min_duration_statement: "1000"
      log_statement: "ddl"

  bootstrap:
    initdb:
      database: monitor
      owner: fluodata
      secret:
        name: fluodata-pg-credentials
  # Backup config (commented — enable when S3 endpoint is available)
  # backup:
  #   barmanObjectStore:
  #     destinationPath: "s3://fluodata-backups/pg/"
  #     s3Credentials:
  #       accessKeyId:
  #         name: s3-credentials
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: s3-credentials
  #         key: SECRET_ACCESS_KEY
  #   retentionPolicy: "30d"
