# NetworkPolicies for all application namespaces.
# These implement a default-deny + allow-list approach per REQUIREMENTS.md.
#
# Policy overview:
#   - Default deny all ingress in each namespace
#   - Allow intra-namespace communication
#   - Allow ingress controller -> app pods
#   - Allow monitoring scraping (VictoriaMetrics VMAgent)
#   - Allow DNS resolution (kube-system/CoreDNS)
#   - Allow app -> database/broker connections
---
# ============================================================
# fluodata namespace
# ============================================================

# Default deny all ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: fluodata
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow intra-namespace traffic (pods within fluodata can talk to each other)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: fluodata
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Allow ingress-nginx -> fluodata pods (HTTP traffic from ingress controller)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress
  namespace: fluodata
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
---
# Allow monitoring scraping (VMAgent -> app pods metrics endpoints)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: fluodata
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
---
# Allow MQTT external traffic to RabbitMQ (LoadBalancer service)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mqtt-external
  namespace: fluodata
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 1883
---
# ============================================================
# longhorn-system namespace
# ============================================================

# Default deny ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow intra-namespace (Longhorn components communicate heavily)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Allow monitoring scraping
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
---
# Allow all namespaces to reach Longhorn CSI (storage provisioning)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-csi-from-all
  namespace: longhorn-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
---
# Allow kube-apiserver to reach Longhorn admission webhook.
# With Cilium VXLAN tunneling + kube-proxy replacement, the API server's host IP
# (10.10.0.x) is translated to a pod CIDR address (10.244.x.x) when the target pod
# is on a different node. We must allow from the entire pod CIDR.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: longhorn-system
spec:
  podSelector:
    matchLabels:
      app: longhorn-manager
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9502
      from:
        - ipBlock:
            cidr: 10.10.0.0/24
        - ipBlock:
            cidr: 10.244.0.0/16
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
---
# ============================================================
# monitoring namespace
# ============================================================

# Default deny ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow intra-namespace (Grafana -> VMSingle, VMAgent -> VMSingle, etc.)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Allow ingress-nginx -> Grafana (dashboard access)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
---
# Allow VMAgent to scrape all namespaces (VMAgent pods need to reach
# target pods for metrics collection — targets connect back to VMAgent)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-scrape-targets
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
---
# Allow kube-apiserver to reach VictoriaMetrics operator webhook.
# With Cilium VXLAN tunneling + kube-proxy replacement, the API server's host IP
# is translated to a pod CIDR address when crossing nodes. Allow both CIDRs.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-stack
      app.kubernetes.io/name: victoria-metrics-operator
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9443
      from:
        - ipBlock:
            cidr: 10.10.0.0/24
        - ipBlock:
            cidr: 10.244.0.0/16
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
---
# ============================================================
# logging namespace
# ============================================================

# Default deny ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: logging
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow intra-namespace (Promtail -> Loki)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: logging
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Allow Grafana (monitoring ns) -> Loki (logging ns) for log queries
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: logging
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
---
# ============================================================
# ingress-nginx namespace
# ============================================================

# Default deny ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: ingress-nginx
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow external traffic to ingress controller (HTTP/HTTPS)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-http
  namespace: ingress-nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
# Allow kube-apiserver to reach ingress-nginx admission webhook.
# With Cilium VXLAN tunneling, API server source IP is from pod CIDR.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: ingress-nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
      from:
        - ipBlock:
            cidr: 10.10.0.0/24
        - ipBlock:
            cidr: 10.244.0.0/16
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
---
# Allow monitoring scraping
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: ingress-nginx
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
---
# ============================================================
# cert-manager namespace
# ============================================================

# Default deny ingress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Allow intra-namespace (cert-manager components)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
# Allow monitoring scraping
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-monitoring
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
---
# Allow kube-apiserver to reach cert-manager webhook for admission validation.
# With Cilium VXLAN tunneling + kube-proxy replacement, when the API server
# (host network 10.10.0.10) calls a webhook pod on a different node, Cilium
# encapsulates the packet and the source IP becomes the node's Cilium router
# address in the pod CIDR (10.244.x.x), not the original host IP. We must
# allow from both the host network and the entire pod CIDR.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: webhook
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 10250
      from:
        - ipBlock:
            cidr: 10.10.0.0/24
        - ipBlock:
            cidr: 10.244.0.0/16
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
